apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-demo-chart.fullname" . }}
  labels:
    {{- include "otus-demo-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otus-demo-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otus-demo-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: web
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: otus-demo-secret
                  key: DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: otus-demo-secret
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otus-demo-secret
                  key: DATASOURCE_PASSWORD      
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 120
            periodSeconds: 5
