apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-api-gateway-chart.fullname" . }}
  labels:
    {{- include "otus-api-gateway-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otus-api-gateway-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otus-api-gateway-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: USER_URL
              value: {{ .Values.services.user.url }}
            - name: AUTH_URL
              value: {{ .Values.services.auth.url }}
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 120
            periodSeconds: 5
